FROM debian:8
MAINTAINER Oldrich Vykydal sysadmin@klokantech.com
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -qq update && apt-get install -y apt-utils && apt-get upgrade -y
RUN apt-get install -y varnish
RUN rm -rf /var/lib/apt/lists/*

ADD start.sh /start.sh
#COPY default.vcl /etc/varnish/default.vcl
#COPY start.sh	/ect/varnish/start.sh

ENV VCL_CONFIG      /etc/varnish/default.vcl
ENV CACHE_SIZE      1024m
ENV VARNISHD_PARAMS -p default_ttl=3600 -p default_grace=3600

CMD ["/start.sh"]

EXPOSE 80
